import React, { useEffect, useRef, useState } from 'react'
import { Camera, CheckCircle2, Clock3, Upload, XCircle } from 'lucide-react'
import { api, json } from '../api'
import WebcamCapture from '../components/WebcamCapture'

export default function Guard(){
 const [mode,setMode]=useState('ID_ONLY'),[idFile,setIdFile]=useState(null),[liveFile,setLiveFile]=useState(null),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[recent,setRecent]=useState([]); const cam=useRef()
 const refresh=()=>json('/attendance/today').then(setRecent).catch(()=>{}); useEffect(()=>{refresh()},[])
 async function scan(){setBusy(true);setResult(null);try{let id=idFile||await cam.current?.capture();if(!id)throw new Error('Start the camera or choose an ID image.');const f=new FormData();if(mode==='ID_ONLY'){f.append('image',id,'id.jpg')}else{f.append('id_image',id,'id.jpg');if(!liveFile)throw new Error('Choose a live-face image for ID + Live mode.');f.append('live_image',liveFile)}const r=await api(mode==='ID_ONLY'?'/verification/id-image':'/verification/id-live',{method:'POST',body:f});setResult(await r.json());refresh()}catch(e){setResult({status:'ERROR',message:e.message})}finally{setBusy(false)}}
 return <><header><div><p className="eyebrow">SECURITY CONSOLE</p><h1>Attendance scanner</h1><p>Position the student ID inside the guide.</p></div><div className="mode"><button className={mode==='ID_ONLY'?'selected':''} onClick={()=>setMode('ID_ONLY')}>ID only</button><button className={mode==='ID_LIVE'?'selected':''} onClick={()=>setMode('ID_LIVE')}>ID + live face</button></div></header><div className="guard-grid"><section className="panel scanner"><WebcamCapture ref={cam}/><div className="scan-actions"><label className="secondary"><Upload size={17}/> Upload ID<input type="file" accept="image/*" onChange={e=>setIdFile(e.target.files[0])}/></label>{mode==='ID_LIVE'&&<label className="secondary"><Upload size={17}/> Live photo<input type="file" accept="image/*" onChange={e=>setLiveFile(e.target.files[0])}/></label>}<button className="primary" onClick={scan} disabled={busy}><Camera size={18}/>{busy?'Verifying…':'Verify & mark present'}</button></div></section><section className={`panel result ${result?.status?.toLowerCase()||''}`}>{!result?<div className="empty"><div className="pulse"><Camera/></div><h3>Ready to scan</h3><p>Results appear here after verification.</p></div>:<><div className="result-icon">{['RECORDED','DUPLICATE'].includes(result.status)?<CheckCircle2/>:<XCircle/>}</div><p className="eyebrow">{result.status}</p><h2>{result.student?.name||'Verification failed'}</h2>{result.student&&<><p>{result.student.student_id} · {result.student.department}</p><img className="avatar" src={`http://localhost:8000${result.student.photo_url}`}/><div className="scores"><span>ID similarity <b>{result.similarity_score?.toFixed(3)}</b></span>{result.live_similarity_score!=null&&<span>Live similarity <b>{result.live_similarity_score.toFixed(3)}</b></span>}</div></>}<p className="message">{result.message}</p></>}</section></div><section className="panel recent"><h2><Clock3/> Today’s recent attendance</h2><AttendanceRows rows={recent}/></section></>
}
function AttendanceRows({rows}){return <div className="table-wrap"><table><thead><tr><th>Student</th><th>Department</th><th>Time</th><th>Method</th><th>Similarity</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.name}</b><small>{r.student_id}</small></td><td>{r.department}</td><td>{new Date(r.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</td><td><span className="pill">{r.verification_mode.replaceAll('_',' + ')}</span></td><td>{r.similarity_score.toFixed(3)}</td></tr>)}{!rows.length&&<tr><td colSpan="5" className="no-data">No attendance recorded today.</td></tr>}</tbody></table></div>}
